import { Copy, Download, ImagePlus, Plus, Printer, RotateCcw, Sparkles, Trash2 } from 'lucide-react';
import { DEFAULT_FLYER_PRODUCT, FLYER_TEMPLATES } from '../utils/flyerOptions.js';
import { createId } from '../utils/id.js';

const inputClass = 'mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none transition focus:border-red-500 focus:bg-white focus:ring-4 focus:ring-red-100';

function readImage(file, callback) {
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => callback(reader.result);
  reader.readAsDataURL(file);
}

export function FlyerEditor({ flyer, onChange, onExport, onPrint, onReset }) {
  const update = (field) => (event) => onChange({ ...flyer, [field]: event.target.type === 'checkbox' ? event.target.checked : event.target.value });
  const applyTemplate = (key) => onChange({ ...flyer, template: key, ...FLYER_TEMPLATES[key].colors });
  const updateProduct = (index, field, value) => onChange({ ...flyer, products: flyer.products.map((product, itemIndex) => itemIndex === index ? { ...product, [field]: value } : product) });
  const addProduct = () => onChange({ ...flyer, products: [...flyer.products, { ...DEFAULT_FLYER_PRODUCT, id: createId() }] });
  const duplicateProduct = (index) => onChange({ ...flyer, products: [...flyer.products.slice(0, index + 1), { ...flyer.products[index], id: createId() }, ...flyer.products.slice(index + 1)] });
  const removeProduct = (index) => onChange({ ...flyer, products: flyer.products.filter((_, itemIndex) => itemIndex !== index) });
  const colorFields = [['background', 'Fondo'], ['header', 'Cabecera'], ['headerText', 'Texto cabecera'], ['accent', 'Acento'], ['card', 'Tarjetas'], ['price', 'Precios'], ['text', 'Textos'], ['border', 'Bordes']];

  return (
    <section className="no-print rounded-[2rem] bg-white p-5 shadow-[0_20px_70px_rgba(15,23,42,.08)] sm:p-7">
      <div className="mb-7 flex items-start gap-3"><div className="rounded-2xl bg-red-600 p-3 text-white"><Sparkles /></div><div><p className="text-xs font-black uppercase tracking-[.25em] text-red-600">Nuevo estudio</p><h1 className="text-3xl font-black text-slate-950">Generador de folletos</h1><p className="mt-2 text-sm leading-6 text-slate-500">Armá una pieza completa con productos, imágenes, descuentos y colores propios.</p></div></div>

      <div className="space-y-7">
        <fieldset><legend className="text-sm font-black text-slate-900">1. Elegí un estilo</legend><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(FLYER_TEMPLATES).map(([key, template]) => <button key={key} type="button" onClick={() => applyTemplate(key)} className={`overflow-hidden rounded-2xl border-2 text-left transition ${flyer.template === key ? 'border-red-600 ring-4 ring-red-100' : 'border-slate-100 hover:border-slate-300'}`}><div className="h-16 p-2" style={{ background: template.colors.background }}><div className="h-5 rounded-md" style={{ background: template.colors.header }} /><div className="mt-2 grid grid-cols-2 gap-1"><i className="h-6 rounded bg-white" /><i className="h-6 rounded bg-white" /></div></div><div className="p-2"><p className="truncate text-xs font-black">{template.label}</p><p className="truncate text-[10px] text-slate-400">{template.description}</p></div></button>)}</div></fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">2. Encabezado y formato</legend><div className="grid gap-4 sm:grid-cols-2"><label>Nombre del negocio<input className={inputClass} value={flyer.businessName} onChange={update('businessName')} /></label><label>Título principal<input className={inputClass} value={flyer.title} onChange={update('title')} /></label><label className="sm:col-span-2">Bajada promocional<input className={inputClass} value={flyer.subtitle} onChange={update('subtitle')} /></label><label>Vigencia<input className={inputClass} value={flyer.validity} onChange={update('validity')} /></label><label>Texto legal / pie<input className={inputClass} value={flyer.footer} onChange={update('footer')} /></label><label>Tamaño<select className={inputClass} value={flyer.size} onChange={update('size')}><option>A4</option><option>A5</option></select></label><label>Orientación<select className={inputClass} value={flyer.orientation} onChange={update('orientation')}><option value="portrait">Vertical</option><option value="landscape">Horizontal</option></select></label><label>Columnas<select className={inputClass} value={flyer.columns} onChange={update('columns')}><option value="2">2 columnas</option><option value="3">3 columnas</option><option value="4">4 columnas</option></select></label><label>Separación de tarjetas<input className="mt-3 w-full accent-red-600" type="range" min="4" max="28" value={flyer.cardGap} onChange={update('cardGap')} /></label></div>
          <div className="mt-4 grid grid-cols-2 gap-3"><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-red-600" type="checkbox" checked={flyer.showDiscount} onChange={update('showDiscount')} />Mostrar descuento</label><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-red-600" type="checkbox" checked={flyer.showOldPrice} onChange={update('showOldPrice')} />Precio anterior</label><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-red-600" type="checkbox" checked={flyer.showDescription} onChange={update('showDescription')} />Descripción</label></div>
        </fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">3. Marca e imágenes</legend><div className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 p-4 text-sm font-black text-slate-600"><ImagePlus size={18} /> {flyer.logo ? 'Cambiar logo' : 'Subir logo'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (logo) => onChange({ ...flyer, logo }))} /></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 p-4 text-sm font-black text-slate-600"><ImagePlus size={18} /> {flyer.bannerImage ? 'Cambiar cabecera' : 'Imagen de cabecera'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (bannerImage) => onChange({ ...flyer, bannerImage }))} /></label></div>{flyer.bannerImage && <label className="mt-4 block text-xs font-bold">Opacidad de imagen: {flyer.bannerOpacity}%<input className="mt-2 w-full accent-red-600" type="range" min="0" max="80" value={flyer.bannerOpacity} onChange={update('bannerOpacity')} /></label>}</fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">4. Colores y terminación</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{colorFields.map(([field, label]) => <label key={field} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2"><input type="color" value={flyer[field]} onChange={update(field)} className="h-9 w-10 cursor-pointer rounded border-0 bg-transparent" /><span className="text-[11px] font-bold">{label}</span></label>)}</div><label className="mt-4 block text-xs font-bold">Redondeado de tarjetas: {flyer.cardRadius}px<input className="mt-2 w-full accent-red-600" type="range" min="0" max="40" value={flyer.cardRadius} onChange={update('cardRadius')} /></label></fieldset>

        <fieldset><div className="flex items-center justify-between"><legend className="text-sm font-black">5. Productos ({flyer.products.length})</legend><button type="button" onClick={addProduct} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-3 py-2 text-xs font-black text-white"><Plus size={16} /> Agregar producto</button></div><div className="mt-3 space-y-3">{flyer.products.map((product, index) => <article key={product.id || index} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-slate-950 px-3 py-1 text-xs font-black text-white">Producto {index + 1}</span><div className="flex gap-1"><button type="button" onClick={() => duplicateProduct(index)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Duplicar"><Copy size={16} /></button><button type="button" onClick={() => removeProduct(index)} disabled={flyer.products.length === 1} className="rounded-lg p-2 text-red-600 hover:bg-red-50 disabled:opacity-30" title="Eliminar"><Trash2 size={16} /></button></div></div><div className="grid gap-3 sm:grid-cols-2"><label>Nombre<input className={inputClass} value={product.name} onChange={(event) => updateProduct(index, 'name', event.target.value)} /></label><label>Descripción<input className={inputClass} value={product.description} onChange={(event) => updateProduct(index, 'description', event.target.value)} /></label><label>Precio<input className={inputClass} value={product.price} onChange={(event) => updateProduct(index, 'price', event.target.value)} /></label><label>Precio anterior<input className={inputClass} value={product.oldPrice} onChange={(event) => updateProduct(index, 'oldPrice', event.target.value)} /></label><label>Descuento<input className={inputClass} value={product.discount} onChange={(event) => updateProduct(index, 'discount', event.target.value)} placeholder="30%" /></label><label className="flex cursor-pointer items-center justify-center gap-2 self-end rounded-xl border-2 border-dashed border-slate-200 px-3 py-2.5 text-xs font-black"><ImagePlus size={16} /> {product.image ? 'Cambiar imagen' : 'Subir imagen'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (image) => updateProduct(index, 'image', image))} /></label></div><label className="mt-3 block text-xs font-bold"><input type="checkbox" className="mr-2 accent-red-600" checked={product.featured} onChange={(event) => updateProduct(index, 'featured', event.target.checked)} />Destacar producto</label></article>)}</div></fieldset>
      </div>

      <div className="mt-7 grid grid-cols-2 gap-3"><button onClick={onExport} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-red-600 px-4 py-3 font-black text-white"><Download size={18} /> Generar PDF</button><button onClick={onPrint} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 font-black text-white"><Printer size={18} /> Imprimir</button><button onClick={onReset} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 px-4 py-3 font-black text-slate-600"><RotateCcw size={18} /> Restablecer folleto</button></div>
    </section>
  );
}
