import { Copy, Download, ImagePlus, Plus, Printer, RotateCcw, Sparkles, Tags, Trash2 } from 'lucide-react';
import { DEFAULT_FLYER_PRODUCT, FLYER_TEMPLATES, getFlyerLayout } from '../utils/flyerOptions.js';
import { createId } from '../utils/id.js';

const inputClass = 'mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none transition focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100';

function readImage(file, callback) {
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => callback(reader.result);
  reader.readAsDataURL(file);
}

export function FlyerEditor({ flyer, onChange, onExport, onPrint, onReset }) {
  const update = (field) => (event) => onChange({ ...flyer, [field]: event.target.type === 'checkbox' ? event.target.checked : event.target.value });
  const applyTemplate = (key) => {
    const template = FLYER_TEMPLATES[key];
    const products = template.promotionDefaults ? flyer.products.map((product) => ({ ...product, ...template.promotionDefaults })) : flyer.products;
    onChange({ ...flyer, template: key, products, ...template.contentDefaults, ...template.colors });
  };
  const updateProduct = (index, field, value) => onChange({ ...flyer, products: flyer.products.map((product, itemIndex) => itemIndex === index ? { ...product, [field]: value } : product) });
  const addProduct = () => onChange({ ...flyer, products: [...flyer.products, { ...DEFAULT_FLYER_PRODUCT, id: createId() }] });
  const duplicateProduct = (index) => onChange({ ...flyer, products: [...flyer.products.slice(0, index + 1), { ...flyer.products[index], id: createId() }, ...flyer.products.slice(index + 1)] });
  const removeProduct = (index) => onChange({ ...flyer, products: flyer.products.filter((_, itemIndex) => itemIndex !== index) });
  const colorFields = [['background', 'Fondo'], ['header', 'Cabecera'], ['headerText', 'Texto cabecera'], ['accent', 'Acento'], ['card', 'Tarjetas'], ['price', 'Precios'], ['text', 'Textos'], ['border', 'Bordes']];
  const layout = getFlyerLayout(flyer.products.length, flyer.orientation, flyer.columns, flyer.automaticLayout);
  const applyPromotionPreset = (index, promotionType, buyQuantity, payQuantity = 1) => {
    onChange({ ...flyer, products: flyer.products.map((product, itemIndex) => itemIndex === index ? { ...product, promotionType, buyQuantity, payQuantity } : product) });
  };
  const applyQuickPromotion = ({ quantity, price, title }) => {
    const template = FLYER_TEMPLATES.threeForThousand;
    const products = flyer.products.map((product) => ({ ...product, promotionType: 'bundle', buyQuantity: quantity, bundlePrice: price, featured: true }));
    onChange({ ...flyer, template: 'threeForThousand', products, title, subtitle: 'Elegí tus favoritos y aprovechá', validity: 'PROMOCIÓN POR TIEMPO LIMITADO', ...template.colors });
  };
  const quickPromotions = [
    { quantity: 3, price: '1.000', title: '¡3 POR $1.000!' },
    { quantity: 2, price: '1.000', title: '¡2 POR $1.000!' },
    { quantity: 3, price: '2.000', title: '¡3 POR $2.000!' },
  ];

  return (
    <section className="no-print rounded-[2rem] bg-white p-5 shadow-[0_20px_70px_rgba(15,23,42,.08)] sm:p-7">
      <div className="mb-7 flex items-start gap-3"><div className="rounded-2xl bg-emerald-600 p-3 text-white"><Sparkles /></div><div><p className="text-xs font-black uppercase tracking-[.25em] text-emerald-600">Nuevo estudio</p><h1 className="text-3xl font-black text-slate-950">Generador de folletos</h1><p className="mt-2 text-sm leading-6 text-slate-500">Armá una pieza completa con productos, imágenes, descuentos y colores propios.</p></div></div>

      <div className="space-y-7">
        <fieldset className="overflow-hidden rounded-3xl border border-lime-300 bg-[#07130d] p-4 text-white shadow-[0_14px_35px_rgba(6,39,25,.18)]"><legend className="flex items-center gap-2 rounded-full bg-lime-400 px-3 py-1 text-xs font-black uppercase tracking-wider text-[#07130d]"><Tags size={15} /> Plantillas de promociones</legend><p className="mt-2 text-xs text-emerald-100/70">Accesos rápidos siempre visibles. Después podés editar cantidad, precio, textos y colores.</p><div className="mt-3 grid grid-cols-3 gap-2">{quickPromotions.map((promotion) => <button type="button" key={promotion.title} onClick={() => applyQuickPromotion(promotion)} className={`rounded-2xl border px-2 py-3 text-center transition hover:-translate-y-0.5 ${flyer.template === 'threeForThousand' && flyer.title === promotion.title ? 'border-lime-300 bg-lime-400 text-[#07130d] ring-2 ring-lime-300/30' : 'border-white/15 bg-white/[.07] text-white hover:border-lime-300/60'}`}><strong className="block text-lg font-black leading-none">{promotion.quantity} × ${promotion.price}</strong><small className="mt-1 block text-[10px] font-bold opacity-70">Aplicar plantilla</small></button>)}</div></fieldset>
        <fieldset><legend className="text-sm font-black text-slate-900">1. Elegí un estilo</legend><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(FLYER_TEMPLATES).map(([key, template]) => <button key={key} type="button" onClick={() => applyTemplate(key)} className={`overflow-hidden rounded-2xl border-2 text-left transition ${flyer.template === key ? 'border-emerald-600 ring-4 ring-emerald-100' : 'border-slate-100 hover:border-slate-300'}`}><div className="h-16 p-2" style={{ background: template.colors.background }}><div className="h-5 rounded-md" style={{ background: template.colors.header }} /><div className="mt-2 grid grid-cols-2 gap-1"><i className="h-6 rounded bg-white" /><i className="h-6 rounded bg-white" /></div></div><div className="p-2"><p className="truncate text-xs font-black">{template.label}</p><p className="truncate text-[10px] text-slate-400">{template.description}</p></div></button>)}</div></fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">2. Encabezado y formato</legend><div className="grid gap-4 sm:grid-cols-2"><label>Nombre del negocio<input className={inputClass} value={flyer.businessName} onChange={update('businessName')} /></label><label>Título principal<input className={inputClass} value={flyer.title} onChange={update('title')} /></label><label className="sm:col-span-2">Bajada promocional<input className={inputClass} value={flyer.subtitle} onChange={update('subtitle')} /></label><label>Vigencia<input className={inputClass} value={flyer.validity} onChange={update('validity')} /></label><label>Texto legal / pie<input className={inputClass} value={flyer.footer} onChange={update('footer')} /></label><label>Tamaño<select className={inputClass} value={flyer.size} onChange={update('size')}><option>A4</option><option>A5</option></select></label><label>Orientación<select className={inputClass} value={flyer.orientation} onChange={update('orientation')}><option value="portrait">Vertical</option><option value="landscape">Horizontal</option></select></label><label className={flyer.automaticLayout ? 'opacity-45' : ''}>Columnas<select disabled={flyer.automaticLayout} className={inputClass} value={flyer.columns} onChange={update('columns')}><option value="2">2 columnas</option><option value="3">3 columnas</option><option value="4">4 columnas</option></select></label><label>Separación de tarjetas<input className="mt-3 w-full accent-emerald-600" type="range" min="4" max="28" value={flyer.cardGap} onChange={update('cardGap')} /></label></div>
          <label className="mt-4 flex cursor-pointer items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-3"><input className="mt-0.5 h-5 w-5 accent-emerald-600" type="checkbox" checked={flyer.automaticLayout} onChange={update('automaticLayout')} /><span><strong className="block text-sm text-emerald-950">Acomodar productos automáticamente</strong><small className="text-emerald-700">Actualmente usa {layout.columns} columnas × {layout.rows} filas y ajusta imágenes, textos y precios.</small></span></label>
          <div className="mt-4 grid grid-cols-2 gap-3"><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-emerald-600" type="checkbox" checked={flyer.showDiscount} onChange={update('showDiscount')} />Mostrar descuento</label><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-emerald-600" type="checkbox" checked={flyer.showOldPrice} onChange={update('showOldPrice')} />Precio anterior</label><label className="rounded-xl bg-slate-50 p-3 text-xs font-bold"><input className="mr-2 accent-emerald-600" type="checkbox" checked={flyer.showDescription} onChange={update('showDescription')} />Descripción</label></div>
        </fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">3. Marca e imágenes</legend><div className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 p-4 text-sm font-black text-slate-600"><ImagePlus size={18} /> {flyer.logo ? 'Cambiar logo' : 'Subir logo'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (logo) => onChange({ ...flyer, logo }))} /></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 p-4 text-sm font-black text-slate-600"><ImagePlus size={18} /> {flyer.bannerImage ? 'Cambiar cabecera' : 'Imagen de cabecera'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (bannerImage) => onChange({ ...flyer, bannerImage }))} /></label></div>{flyer.bannerImage && <label className="mt-4 block text-xs font-bold">Opacidad de imagen: {flyer.bannerOpacity}%<input className="mt-2 w-full accent-emerald-600" type="range" min="0" max="80" value={flyer.bannerOpacity} onChange={update('bannerOpacity')} /></label>}</fieldset>

        <fieldset className="rounded-3xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">4. Colores y terminación</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{colorFields.map(([field, label]) => <label key={field} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2"><input type="color" value={flyer[field]} onChange={update(field)} className="h-9 w-10 cursor-pointer rounded border-0 bg-transparent" /><span className="text-[11px] font-bold">{label}</span></label>)}</div><label className="mt-4 block text-xs font-bold">Redondeado de tarjetas: {flyer.cardRadius}px<input className="mt-2 w-full accent-emerald-600" type="range" min="0" max="40" value={flyer.cardRadius} onChange={update('cardRadius')} /></label></fieldset>

        <fieldset><div className="flex items-center justify-between"><legend className="text-sm font-black">5. Productos ({flyer.products.length})</legend><button type="button" onClick={addProduct} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white"><Plus size={16} /> Agregar producto</button></div><div className="mt-3 space-y-3">{flyer.products.map((product, index) => <article key={product.id || index} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-slate-950 px-3 py-1 text-xs font-black text-white">Producto {index + 1}</span><div className="flex gap-1"><button type="button" onClick={() => duplicateProduct(index)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Duplicar"><Copy size={16} /></button><button type="button" onClick={() => removeProduct(index)} disabled={flyer.products.length === 1} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50 disabled:opacity-30" title="Eliminar"><Trash2 size={16} /></button></div></div><div className="grid gap-3 sm:grid-cols-2"><label>Nombre<input className={inputClass} value={product.name} onChange={(event) => updateProduct(index, 'name', event.target.value)} /></label><label>Descripción<input className={inputClass} value={product.description} onChange={(event) => updateProduct(index, 'description', event.target.value)} /></label><label>Precio unitario<input className={inputClass} value={product.price} onChange={(event) => updateProduct(index, 'price', event.target.value)} /></label><label>Precio anterior<input className={inputClass} value={product.oldPrice} onChange={(event) => updateProduct(index, 'oldPrice', event.target.value)} /></label></div>
          <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs font-black uppercase tracking-wide text-emerald-900">Tipo de promoción</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{[['discount', '% OFF'], ['payLess', '3×2'], ['bundle', '3×$'], ['custom', 'Libre']].map(([type, label]) => <button type="button" key={type} onClick={() => applyPromotionPreset(index, type, 3, 2)} className={`rounded-xl px-2 py-2 text-xs font-black transition ${product.promotionType === type ? 'bg-emerald-700 text-white' : 'bg-white text-emerald-900 hover:bg-emerald-100'}`}>{label}</button>)}</div>
            <div className="mt-3 grid grid-cols-2 gap-3">{product.promotionType === 'discount' && <label>Descuento<input className={inputClass} value={product.discount} onChange={(event) => updateProduct(index, 'discount', event.target.value)} placeholder="30%" /></label>}{product.promotionType === 'payLess' && <><label>Llevás<input className={inputClass} type="number" min="2" value={product.buyQuantity} onChange={(event) => updateProduct(index, 'buyQuantity', event.target.value)} /></label><label>Pagás<input className={inputClass} type="number" min="1" value={product.payQuantity} onChange={(event) => updateProduct(index, 'payQuantity', event.target.value)} /></label></>}{product.promotionType === 'bundle' && <><label>Cantidad<input className={inputClass} type="number" min="2" value={product.buyQuantity} onChange={(event) => updateProduct(index, 'buyQuantity', event.target.value)} /></label><label>Precio del combo<input className={inputClass} value={product.bundlePrice} onChange={(event) => updateProduct(index, 'bundlePrice', event.target.value)} placeholder="2.999" /></label></>}{product.promotionType === 'custom' && <label className="col-span-2">Texto promocional<input className={inputClass} value={product.promotionText || ''} onChange={(event) => updateProduct(index, 'promotionText', event.target.value)} placeholder="Ej: 4 unidades por precio especial" /></label>}</div>
          </div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-200 px-3 py-2.5 text-xs font-black"><ImagePlus size={16} /> {product.image ? 'Cambiar imagen' : 'Subir imagen'}<input className="sr-only" type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0], (image) => updateProduct(index, 'image', image))} /></label><label className="flex items-center text-xs font-bold"><input type="checkbox" className="mr-2 accent-emerald-600" checked={product.featured} onChange={(event) => updateProduct(index, 'featured', event.target.checked)} />Destacar producto</label></div></article>)}</div></fieldset>
      </div>

      <div className="mt-7 grid grid-cols-2 gap-3"><button onClick={onExport} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-4 py-3 font-black text-white"><Download size={18} /> Generar PDF</button><button onClick={onPrint} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 font-black text-white"><Printer size={18} /> Imprimir</button><button onClick={onReset} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 px-4 py-3 font-black text-slate-600"><RotateCcw size={18} /> Restablecer folleto</button></div>
    </section>
  );
}
